project_id = "iyympxxzrnhkpcftoquv"

[functions.analyze-chart]
verify_jwt = true

[functions.analyze-news-impact]
verify_jwt = true

[functions.fetch-forex-news]
verify_jwt = false

[functions.generate-news-expectations]
verify_jwt = false

[functions.get-exchange-rate]
verify_jwt = false

[functions.initiate-mpesa-payment]
verify_jwt = true

[functions.handle-lipana-webhook]
verify_jwt = false

[functions.create-user-account]
verify_jwt = false

[functions.send-account-request]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.capture-paypal-order]
verify_jwt = true

[functions.create-paypal-order]
verify_jwt = true

[functions.send-contact-query]
verify_jwt = false

[functions.respond-contact-query]
verify_jwt = true

[functions.send-admin-email]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false